<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>dev.baust.showalltables</groupId>
    <artifactId>show-all-tables-plugin</artifactId>
    <version>1.0.0</version>
    <name>show-all-tables-plugin</name>
    <properties>
        <release>2.0 FP21, 3.0 FP2502, n/a</release>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <version.ENV>3.2502.5</version.ENV>
        <asciidoctor.maven.plugin.version>2.2.2</asciidoctor.maven.plugin.version>
    </properties>
    <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>false</filtering>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <configuration>
                    <archive>
                        <manifest>
                            <addClasspath/>
                            <addDefaultImplementationEntries/>
                            <addDefaultSpecificationEntries/>
                            <addExtensions/>
                            <classpathLayoutType/>
                            <classpathPrefix/>
                            <customClasspathLayout/>
                            <mainClass/>
                            <packageName>dev.baust.showalltables</packageName>
                            <useUniqueVersions/>
                        </manifest>
                        <manifestEntries>
                            <pluginName>${pom.name}</pluginName>
                            <cashdeskPOSPlugin>dev.baust.showalltables.ShowAllTablesPlugin</cashdeskPOSPlugin>
                            <cashDeskVersions>${release}</cashDeskVersions>
                            <version>${pom.version}</version>
                            <build-number>${BITBUCKET_BUILD_NUMBER}</build-number>
                            <ci-build-number>${BITBUCKET_BUILD_NUMBER}</ci-build-number>
                            <commit-id>${BITBUCKET_COMMIT}</commit-id>
                        </manifestEntries>
                    </archive>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.0</version>
                <configuration>
                    <source>11</source>
                    <target>11</target>
                </configuration>
            </plugin>
        </plugins>
    </build>
    <dependencies>
        <dependency>
            <groupId>com.sap.customercheckout.pos</groupId>
            <artifactId>ENV</artifactId>
            <version>${version.ENV}</version>
            <scope>provided</scope>
            <exclusions>
                <exclusion>
                    <groupId>javax.servlet</groupId>
                    <artifactId>javax.servlet-api</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
    </dependencies>

    <distributionManagement>
        <repository>
            <id>github</id>
            <name>GitHub Packages</name>
            <url>https://maven.pkg.github.com/stefanbaust/cco-multiplugin-demo</url>
        </repository>
    </distributionManagement>
</project>
